"""add_color_gender_to_pets

Revision ID: dfa2f2e1adb2
Revises: 0002
Create Date: 2026-04-28 21:01:39.530917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dfa2f2e1adb2'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_biometrics_pet_id', table_name='biometrics')
    op.alter_column('pet_guardians', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index('ix_pet_guardians_guardian_id', table_name='pet_guardians')
    op.drop_index('ix_pet_guardians_pet_id', table_name='pet_guardians')
    op.add_column('pets', sa.Column('color', sa.String(length=100), nullable=True))
    op.add_column('pets', sa.Column('gender', sa.String(length=10), nullable=True))
    op.drop_index('ix_pets_owner_id', table_name='pets')
    op.drop_index('ix_pets_status', table_name='pets')
    op.drop_column('pets', 'lng')
    op.drop_column('pets', 'lat')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.add_column('pets', sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pets', sa.Column('lng', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index('ix_pets_status', 'pets', ['status'], unique=False)
    op.create_index('ix_pets_owner_id', 'pets', ['owner_id'], unique=False)
    op.drop_column('pets', 'gender')
    op.drop_column('pets', 'color')
    op.create_index('ix_pet_guardians_pet_id', 'pet_guardians', ['pet_id'], unique=False)
    op.create_index('ix_pet_guardians_guardian_id', 'pet_guardians', ['guardian_id'], unique=False)
    op.alter_column('pet_guardians', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index('ix_biometrics_pet_id', 'biometrics', ['pet_id'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    # ### end Alembic commands ###
